<?php

/**
 * @file
 * Contains commerce_onsitepg.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_onsitepg_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_onsitepg module.
    case 'help.page.commerce_onsitepg':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Onsite Payment Gateway for Commerce') . '</p>';
      return $output;

    default:
  }
}
